export interface ElementData {
  atomicNumber: number;
  symbol: string;
  name: string;
  category: ElementCategory;
  naturallyOccurring: boolean;
  synthetic: boolean;
  crustalAbundance: number;
  commonOre: string | null;
}

export enum ElementCategory {
  AlkaliMetal = 'AlkaliMetal',
  AlkalineEarthMetal = 'AlkalineEarthMetal',
  Lanthanide = 'Lanthanide',
  Actinide = 'Actinide',
  TransitionMetal = 'TransitionMetal',
  PostTransitionMetal = 'PostTransitionMetal',
  Metalloid = 'Metalloid',
  Nonmetal = 'Nonmetal',
  Halogen = 'Halogen',
  NobleGas = 'NobleGas',
  Unknown = 'Unknown',
}

export const ELEMENTS: readonly ElementData[] = [
  { atomicNumber: 1, symbol: 'H', name: 'Hydrogen', category: ElementCategory.Nonmetal, naturallyOccurring: true, synthetic: false, crustalAbundance: 1400, commonOre: null },
  { atomicNumber: 2, symbol: 'He', name: 'Helium', category: ElementCategory.NobleGas, naturallyOccurring: true, synthetic: false, crustalAbundance: 0.008, commonOre: null },
  { atomicNumber: 3, symbol: 'Li', name: 'Lithium', category: ElementCategory.AlkaliMetal, naturallyOccurring: true, synthetic: false, crustalAbundance: 20, commonOre: 'spodumene' },
  { atomicNumber: 4, symbol: 'Be', name: 'Beryllium', category: ElementCategory.AlkalineEarthMetal, naturallyOccurring: true, synthetic: false, crustalAbundance: 2.6, commonOre: 'beryl' },
  { atomicNumber: 5, symbol: 'B', name: 'Boron', category: ElementCategory.Metalloid, naturallyOccurring: true, synthetic: false, crustalAbundance: 10, commonOre: 'borax' },
  { atomicNumber: 6, symbol: 'C', name: 'Carbon', category: ElementCategory.Nonmetal, naturallyOccurring: true, synthetic: false, crustalAbundance: 200, commonOre: 'graphite' },
  { atomicNumber: 7, symbol: 'N', name: 'Nitrogen', category: ElementCategory.Nonmetal, naturallyOccurring: true, synthetic: false, crustalAbundance: 19, commonOre: null },
  { atomicNumber: 8, symbol: 'O', name: 'Oxygen', category: ElementCategory.Nonmetal, naturallyOccurring: true, synthetic: false, crustalAbundance: 460000, commonOre: null },
  { atomicNumber: 9, symbol: 'F', name: 'Fluorine', category: ElementCategory.Halogen, naturallyOccurring: true, synthetic: false, crustalAbundance: 585, commonOre: 'fluorite' },
  { atomicNumber: 10, symbol: 'Ne', name: 'Neon', category: ElementCategory.NobleGas, naturallyOccurring: true, synthetic: false, crustalAbundance: 0.005, commonOre: null },
  { atomicNumber: 11, symbol: 'Na', name: 'Sodium', category: ElementCategory.AlkaliMetal, naturallyOccurring: true, synthetic: false, crustalAbundance: 23600, commonOre: 'halite' },
  { atomicNumber: 12, symbol: 'Mg', name: 'Magnesium', category: ElementCategory.AlkalineEarthMetal, naturallyOccurring: true, synthetic: false, crustalAbundance: 23000, commonOre: 'dolomite' },
  { atomicNumber: 13, symbol: 'Al', name: 'Aluminum', category: ElementCategory.PostTransitionMetal, naturallyOccurring: true, synthetic: false, crustalAbundance: 82000, commonOre: 'bauxite' },
  { atomicNumber: 14, symbol: 'Si', name: 'Silicon', category: ElementCategory.Metalloid, naturallyOccurring: true, synthetic: false, crustalAbundance: 282000, commonOre: 'quartz' },
  { atomicNumber: 15, symbol: 'P', name: 'Phosphorus', category: ElementCategory.Nonmetal, naturallyOccurring: true, synthetic: false, crustalAbundance: 1050, commonOre: 'apatite' },
  { atomicNumber: 16, symbol: 'S', name: 'Sulfur', category: ElementCategory.Nonmetal, naturallyOccurring: true, synthetic: false, crustalAbundance: 350, commonOre: 'sulfur' },
  { atomicNumber: 17, symbol: 'Cl', name: 'Chlorine', category: ElementCategory.Halogen, naturallyOccurring: true, synthetic: false, crustalAbundance: 130, commonOre: 'halite' },
  { atomicNumber: 18, symbol: 'Ar', name: 'Argon', category: ElementCategory.NobleGas, naturallyOccurring: true, synthetic: false, crustalAbundance: 3.5, commonOre: null },
  { atomicNumber: 19, symbol: 'K', name: 'Potassium', category: ElementCategory.AlkaliMetal, naturallyOccurring: true, synthetic: false, crustalAbundance: 21000, commonOre: 'sylvite' },
  { atomicNumber: 20, symbol: 'Ca', name: 'Calcium', category: ElementCategory.AlkalineEarthMetal, naturallyOccurring: true, synthetic: false, crustalAbundance: 41000, commonOre: 'calcite' },
  { atomicNumber: 21, symbol: 'Sc', name: 'Scandium', category: ElementCategory.TransitionMetal, naturallyOccurring: true, synthetic: false, crustalAbundance: 16, commonOre: 'thortveitite' },
  { atomicNumber: 22, symbol: 'Ti', name: 'Titanium', category: ElementCategory.TransitionMetal, naturallyOccurring: true, synthetic: false, crustalAbundance: 5600, commonOre: 'ilmenite' },
  { atomicNumber: 23, symbol: 'V', name: 'Vanadium', category: ElementCategory.TransitionMetal, naturallyOccurring: true, synthetic: false, crustalAbundance: 120, commonOre: 'vanadinite' },
  { atomicNumber: 24, symbol: 'Cr', name: 'Chromium', category: ElementCategory.TransitionMetal, naturallyOccurring: true, synthetic: false, crustalAbundance: 102, commonOre: 'chromite' },
  { atomicNumber: 25, symbol: 'Mn', name: 'Manganese', category: ElementCategory.TransitionMetal, naturallyOccurring: true, synthetic: false, crustalAbundance: 950, commonOre: 'pyrolusite' },
  { atomicNumber: 26, symbol: 'Fe', name: 'Iron', category: ElementCategory.TransitionMetal, naturallyOccurring: true, synthetic: false, crustalAbundance: 56000, commonOre: 'hematite' },
  { atomicNumber: 27, symbol: 'Co', name: 'Cobalt', category: ElementCategory.TransitionMetal, naturallyOccurring: true, synthetic: false, crustalAbundance: 25, commonOre: 'cobaltite' },
  { atomicNumber: 28, symbol: 'Ni', name: 'Nickel', category: ElementCategory.TransitionMetal, naturallyOccurring: true, synthetic: false, crustalAbundance: 84, commonOre: 'pentlandite' },
  { atomicNumber: 29, symbol: 'Cu', name: 'Copper', category: ElementCategory.TransitionMetal, naturallyOccurring: true, synthetic: false, crustalAbundance: 60, commonOre: 'chalcopyrite' },
  { atomicNumber: 30, symbol: 'Zn', name: 'Zinc', category: ElementCategory.TransitionMetal, naturallyOccurring: true, synthetic: false, crustalAbundance: 70, commonOre: 'sphalerite' },
  { atomicNumber: 31, symbol: 'Ga', name: 'Gallium', category: ElementCategory.PostTransitionMetal, naturallyOccurring: true, synthetic: false, crustalAbundance: 19, commonOre: 'gallite' },
  { atomicNumber: 32, symbol: 'Ge', name: 'Germanium', category: ElementCategory.Metalloid, naturallyOccurring: true, synthetic: false, crustalAbundance: 1.5, commonOre: 'germanite' },
  { atomicNumber: 33, symbol: 'As', name: 'Arsenic', category: ElementCategory.Metalloid, naturallyOccurring: true, synthetic: false, crustalAbundance: 1.8, commonOre: 'arsenopyrite' },
  { atomicNumber: 34, symbol: 'Se', name: 'Selenium', category: ElementCategory.Nonmetal, naturallyOccurring: true, synthetic: false, crustalAbundance: 0.05, commonOre: 'selenide' },
  { atomicNumber: 35, symbol: 'Br', name: 'Bromine', category: ElementCategory.Halogen, naturallyOccurring: true, synthetic: false, crustalAbundance: 2.4, commonOre: null },
  { atomicNumber: 36, symbol: 'Kr', name: 'Krypton', category: ElementCategory.NobleGas, naturallyOccurring: true, synthetic: false, crustalAbundance: 0.0001, commonOre: null },
  { atomicNumber: 37, symbol: 'Rb', name: 'Rubidium', category: ElementCategory.AlkaliMetal, naturallyOccurring: true, synthetic: false, crustalAbundance: 90, commonOre: 'lepidolite' },
  { atomicNumber: 38, symbol: 'Sr', name: 'Strontium', category: ElementCategory.AlkalineEarthMetal, naturallyOccurring: true, synthetic: false, crustalAbundance: 370, commonOre: 'celestite' },
  { atomicNumber: 39, symbol: 'Y', name: 'Yttrium', category: ElementCategory.TransitionMetal, naturallyOccurring: true, synthetic: false, crustalAbundance: 33, commonOre: 'xenotime' },
  { atomicNumber: 40, symbol: 'Zr', name: 'Zirconium', category: ElementCategory.TransitionMetal, naturallyOccurring: true, synthetic: false, crustalAbundance: 165, commonOre: 'zircon' },
  { atomicNumber: 41, symbol: 'Nb', name: 'Niobium', category: ElementCategory.TransitionMetal, naturallyOccurring: true, synthetic: false, crustalAbundance: 20, commonOre: 'columbite' },
  { atomicNumber: 42, symbol: 'Mo', name: 'Molybdenum', category: ElementCategory.TransitionMetal, naturallyOccurring: true, synthetic: false, crustalAbundance: 1.2, commonOre: 'molybdenite' },
  { atomicNumber: 43, symbol: 'Tc', name: 'Technetium', category: ElementCategory.TransitionMetal, naturallyOccurring: false, synthetic: true, crustalAbundance: 0, commonOre: null },
  { atomicNumber: 44, symbol: 'Ru', name: 'Ruthenium', category: ElementCategory.TransitionMetal, naturallyOccurring: true, synthetic: false, crustalAbundance: 0.001, commonOre: 'osmiridium' },
  { atomicNumber: 45, symbol: 'Rh', name: 'Rhodium', category: ElementCategory.TransitionMetal, naturallyOccurring: true, synthetic: false, crustalAbundance: 0.0002, commonOre: 'rhodite' },
  { atomicNumber: 46, symbol: 'Pd', name: 'Palladium', category: ElementCategory.TransitionMetal, naturallyOccurring: true, synthetic: false, crustalAbundance: 0.006, commonOre: 'braggite' },
  { atomicNumber: 47, symbol: 'Ag', name: 'Silver', category: ElementCategory.TransitionMetal, naturallyOccurring: true, synthetic: false, crustalAbundance: 0.08, commonOre: 'argentite' },
  { atomicNumber: 48, symbol: 'Cd', name: 'Cadmium', category: ElementCategory.TransitionMetal, naturallyOccurring: true, synthetic: false, crustalAbundance: 0.15, commonOre: 'greenockite' },
  { atomicNumber: 49, symbol: 'In', name: 'Indium', category: ElementCategory.PostTransitionMetal, naturallyOccurring: true, synthetic: false, crustalAbundance: 0.25, commonOre: 'indite' },
  { atomicNumber: 50, symbol: 'Sn', name: 'Tin', category: ElementCategory.PostTransitionMetal, naturallyOccurring: true, synthetic: false, crustalAbundance: 2.2, commonOre: 'cassiterite' },
  { atomicNumber: 51, symbol: 'Sb', name: 'Antimony', category: ElementCategory.Metalloid, naturallyOccurring: true, synthetic: false, crustalAbundance: 0.2, commonOre: 'stibnite' },
  { atomicNumber: 52, symbol: 'Te', name: 'Tellurium', category: ElementCategory.Metalloid, naturallyOccurring: true, synthetic: false, crustalAbundance: 0.001, commonOre: 'telluride' },
  { atomicNumber: 53, symbol: 'I', name: 'Iodine', category: ElementCategory.Halogen, naturallyOccurring: true, synthetic: false, crustalAbundance: 0.45, commonOre: null },
  { atomicNumber: 54, symbol: 'Xe', name: 'Xenon', category: ElementCategory.NobleGas, naturallyOccurring: true, synthetic: false, crustalAbundance: 0.00003, commonOre: null },
  { atomicNumber: 55, symbol: 'Cs', name: 'Cesium', category: ElementCategory.AlkaliMetal, naturallyOccurring: true, synthetic: false, crustalAbundance: 3, commonOre: 'pollucite' },
  { atomicNumber: 56, symbol: 'Ba', name: 'Barium', category: ElementCategory.AlkalineEarthMetal, naturallyOccurring: true, synthetic: false, crustalAbundance: 425, commonOre: 'barite' },
  { atomicNumber: 57, symbol: 'La', name: 'Lanthanum', category: ElementCategory.Lanthanide, naturallyOccurring: true, synthetic: false, crustalAbundance: 39, commonOre: 'monazite' },
  { atomicNumber: 58, symbol: 'Ce', name: 'Cerium', category: ElementCategory.Lanthanide, naturallyOccurring: true, synthetic: false, crustalAbundance: 66.5, commonOre: 'bastnasite' },
  { atomicNumber: 59, symbol: 'Pr', name: 'Praseodymium', category: ElementCategory.Lanthanide, naturallyOccurring: true, synthetic: false, crustalAbundance: 9.2, commonOre: 'monazite' },
  { atomicNumber: 60, symbol: 'Nd', name: 'Neodymium', category: ElementCategory.Lanthanide, naturallyOccurring: true, synthetic: false, crustalAbundance: 41, commonOre: 'monazite' },
  { atomicNumber: 61, symbol: 'Pm', name: 'Promethium', category: ElementCategory.Lanthanide, naturallyOccurring: false, synthetic: true, crustalAbundance: 0, commonOre: null },
  { atomicNumber: 62, symbol: 'Sm', name: 'Samarium', category: ElementCategory.Lanthanide, naturallyOccurring: true, synthetic: false, crustalAbundance: 7.05, commonOre: 'monazite' },
  { atomicNumber: 63, symbol: 'Eu', name: 'Europium', category: ElementCategory.Lanthanide, naturallyOccurring: true, synthetic: false, crustalAbundance: 2, commonOre: 'monazite' },
  { atomicNumber: 64, symbol: 'Gd', name: 'Gadolinium', category: ElementCategory.Lanthanide, naturallyOccurring: true, synthetic: false, crustalAbundance: 6.2, commonOre: 'gadolinite' },
  { atomicNumber: 65, symbol: 'Tb', name: 'Terbium', category: ElementCategory.Lanthanide, naturallyOccurring: true, synthetic: false, crustalAbundance: 1.2, commonOre: 'monazite' },
  { atomicNumber: 66, symbol: 'Dy', name: 'Dysprosium', category: ElementCategory.Lanthanide, naturallyOccurring: true, synthetic: false, crustalAbundance: 5.2, commonOre: 'monazite' },
  { atomicNumber: 67, symbol: 'Ho', name: 'Holmium', category: ElementCategory.Lanthanide, naturallyOccurring: true, synthetic: false, crustalAbundance: 1.3, commonOre: 'monazite' },
  { atomicNumber: 68, symbol: 'Er', name: 'Erbium', category: ElementCategory.Lanthanide, naturallyOccurring: true, synthetic: false, crustalAbundance: 3.5, commonOre: 'monazite' },
  { atomicNumber: 69, symbol: 'Tm', name: 'Thulium', category: ElementCategory.Lanthanide, naturallyOccurring: true, synthetic: false, crustalAbundance: 0.52, commonOre: 'monazite' },
  { atomicNumber: 70, symbol: 'Yb', name: 'Ytterbium', category: ElementCategory.Lanthanide, naturallyOccurring: true, synthetic: false, crustalAbundance: 3.2, commonOre: 'monazite' },
  { atomicNumber: 71, symbol: 'Lu', name: 'Lutetium', category: ElementCategory.Lanthanide, naturallyOccurring: true, synthetic: false, crustalAbundance: 0.8, commonOre: 'monazite' },
  { atomicNumber: 72, symbol: 'Hf', name: 'Hafnium', category: ElementCategory.TransitionMetal, naturallyOccurring: true, synthetic: false, crustalAbundance: 3, commonOre: 'zircon' },
  { atomicNumber: 73, symbol: 'Ta', name: 'Tantalum', category: ElementCategory.TransitionMetal, naturallyOccurring: true, synthetic: false, crustalAbundance: 2, commonOre: 'tantalite' },
  { atomicNumber: 74, symbol: 'W', name: 'Tungsten', category: ElementCategory.TransitionMetal, naturallyOccurring: true, synthetic: false, crustalAbundance: 1.3, commonOre: 'wolframite' },
  { atomicNumber: 75, symbol: 'Re', name: 'Rhenium', category: ElementCategory.TransitionMetal, naturallyOccurring: true, synthetic: false, crustalAbundance: 0.0007, commonOre: 'molybdenite' },
  { atomicNumber: 76, symbol: 'Os', name: 'Osmium', category: ElementCategory.TransitionMetal, naturallyOccurring: true, synthetic: false, crustalAbundance: 0.0015, commonOre: 'osmiridium' },
  { atomicNumber: 77, symbol: 'Ir', name: 'Iridium', category: ElementCategory.TransitionMetal, naturallyOccurring: true, synthetic: false, crustalAbundance: 0.0004, commonOre: 'osmiridium' },
  { atomicNumber: 78, symbol: 'Pt', name: 'Platinum', category: ElementCategory.TransitionMetal, naturallyOccurring: true, synthetic: false, crustalAbundance: 0.005, commonOre: 'sperrylite' },
  { atomicNumber: 79, symbol: 'Au', name: 'Gold', category: ElementCategory.TransitionMetal, naturallyOccurring: true, synthetic: false, crustalAbundance: 0.004, commonOre: 'native_gold' },
  { atomicNumber: 80, symbol: 'Hg', name: 'Mercury', category: ElementCategory.TransitionMetal, naturallyOccurring: true, synthetic: false, crustalAbundance: 0.085, commonOre: 'cinnabar' },
  { atomicNumber: 81, symbol: 'Tl', name: 'Thallium', category: ElementCategory.PostTransitionMetal, naturallyOccurring: true, synthetic: false, crustalAbundance: 0.85, commonOre: 'thallite' },
  { atomicNumber: 82, symbol: 'Pb', name: 'Lead', category: ElementCategory.PostTransitionMetal, naturallyOccurring: true, synthetic: false, crustalAbundance: 14, commonOre: 'galena' },
  { atomicNumber: 83, symbol: 'Bi', name: 'Bismuth', category: ElementCategory.PostTransitionMetal, naturallyOccurring: true, synthetic: false, crustalAbundance: 0.0085, commonOre: 'bismuthinite' },
  { atomicNumber: 84, symbol: 'Po', name: 'Polonium', category: ElementCategory.PostTransitionMetal, naturallyOccurring: true, synthetic: false, crustalAbundance: 0.000000002, commonOre: null },
  { atomicNumber: 85, symbol: 'At', name: 'Astatine', category: ElementCategory.Halogen, naturallyOccurring: true, synthetic: false, crustalAbundance: 0.00000000003, commonOre: null },
  { atomicNumber: 86, symbol: 'Rn', name: 'Radon', category: ElementCategory.NobleGas, naturallyOccurring: true, synthetic: false, crustalAbundance: 0.00000000000004, commonOre: null },
  { atomicNumber: 87, symbol: 'Fr', name: 'Francium', category: ElementCategory.AlkaliMetal, naturallyOccurring: true, synthetic: false, crustalAbundance: 0.000000000000000003, commonOre: null },
  { atomicNumber: 88, symbol: 'Ra', name: 'Radium', category: ElementCategory.AlkalineEarthMetal, naturallyOccurring: true, synthetic: false, crustalAbundance: 0.00000009, commonOre: 'uraninite' },
  { atomicNumber: 89, symbol: 'Ac', name: 'Actinium', category: ElementCategory.Actinide, naturallyOccurring: true, synthetic: false, crustalAbundance: 0.000000055, commonOre: 'uraninite' },
  { atomicNumber: 90, symbol: 'Th', name: 'Thorium', category: ElementCategory.Actinide, naturallyOccurring: true, synthetic: false, crustalAbundance: 9.6, commonOre: 'thorianite' },
  { atomicNumber: 91, symbol: 'Pa', name: 'Protactinium', category: ElementCategory.Actinide, naturallyOccurring: true, synthetic: false, crustalAbundance: 0.0000014, commonOre: 'uraninite' },
  { atomicNumber: 92, symbol: 'U', name: 'Uranium', category: ElementCategory.Actinide, naturallyOccurring: true, synthetic: false, crustalAbundance: 2.7, commonOre: 'uraninite' },
  { atomicNumber: 93, symbol: 'Np', name: 'Neptunium', category: ElementCategory.Actinide, naturallyOccurring: true, synthetic: false, crustalAbundance: 0.0000000002, commonOre: null },
  { atomicNumber: 94, symbol: 'Pu', name: 'Plutonium', category: ElementCategory.Actinide, naturallyOccurring: true, synthetic: false, crustalAbundance: 0, commonOre: null },
  { atomicNumber: 95, symbol: 'Am', name: 'Americium', category: ElementCategory.Actinide, naturallyOccurring: false, synthetic: true, crustalAbundance: 0, commonOre: null },
  { atomicNumber: 96, symbol: 'Cm', name: 'Curium', category: ElementCategory.Actinide, naturallyOccurring: false, synthetic: true, crustalAbundance: 0, commonOre: null },
  { atomicNumber: 97, symbol: 'Bk', name: 'Berkelium', category: ElementCategory.Actinide, naturallyOccurring: false, synthetic: true, crustalAbundance: 0, commonOre: null },
  { atomicNumber: 98, symbol: 'Cf', name: 'Californium', category: ElementCategory.Actinide, naturallyOccurring: false, synthetic: true, crustalAbundance: 0, commonOre: null },
  { atomicNumber: 99, symbol: 'Es', name: 'Einsteinium', category: ElementCategory.Actinide, naturallyOccurring: false, synthetic: true, crustalAbundance: 0, commonOre: null },
  { atomicNumber: 100, symbol: 'Fm', name: 'Fermium', category: ElementCategory.Actinide, naturallyOccurring: false, synthetic: true, crustalAbundance: 0, commonOre: null },
  { atomicNumber: 101, symbol: 'Md', name: 'Mendelevium', category: ElementCategory.Actinide, naturallyOccurring: false, synthetic: true, crustalAbundance: 0, commonOre: null },
  { atomicNumber: 102, symbol: 'No', name: 'Nobelium', category: ElementCategory.Actinide, naturallyOccurring: false, synthetic: true, crustalAbundance: 0, commonOre: null },
  { atomicNumber: 103, symbol: 'Lr', name: 'Lawrencium', category: ElementCategory.Actinide, naturallyOccurring: false, synthetic: true, crustalAbundance: 0, commonOre: null },
  { atomicNumber: 104, symbol: 'Rf', name: 'Rutherfordium', category: ElementCategory.TransitionMetal, naturallyOccurring: false, synthetic: true, crustalAbundance: 0, commonOre: null },
  { atomicNumber: 105, symbol: 'Db', name: 'Dubnium', category: ElementCategory.TransitionMetal, naturallyOccurring: false, synthetic: true, crustalAbundance: 0, commonOre: null },
  { atomicNumber: 106, symbol: 'Sg', name: 'Seaborgium', category: ElementCategory.TransitionMetal, naturallyOccurring: false, synthetic: true, crustalAbundance: 0, commonOre: null },
  { atomicNumber: 107, symbol: 'Bh', name: 'Bohrium', category: ElementCategory.TransitionMetal, naturallyOccurring: false, synthetic: true, crustalAbundance: 0, commonOre: null },
  { atomicNumber: 108, symbol: 'Hs', name: 'Hassium', category: ElementCategory.TransitionMetal, naturallyOccurring: false, synthetic: true, crustalAbundance: 0, commonOre: null },
  { atomicNumber: 109, symbol: 'Mt', name: 'Meitnerium', category: ElementCategory.Unknown, naturallyOccurring: false, synthetic: true, crustalAbundance: 0, commonOre: null },
  { atomicNumber: 110, symbol: 'Ds', name: 'Darmstadtium', category: ElementCategory.Unknown, naturallyOccurring: false, synthetic: true, crustalAbundance: 0, commonOre: null },
  { atomicNumber: 111, symbol: 'Rg', name: 'Roentgenium', category: ElementCategory.Unknown, naturallyOccurring: false, synthetic: true, crustalAbundance: 0, commonOre: null },
  { atomicNumber: 112, symbol: 'Cn', name: 'Copernicium', category: ElementCategory.TransitionMetal, naturallyOccurring: false, synthetic: true, crustalAbundance: 0, commonOre: null },
  { atomicNumber: 113, symbol: 'Nh', name: 'Nihonium', category: ElementCategory.Unknown, naturallyOccurring: false, synthetic: true, crustalAbundance: 0, commonOre: null },
  { atomicNumber: 114, symbol: 'Fl', name: 'Flerovium', category: ElementCategory.Unknown, naturallyOccurring: false, synthetic: true, crustalAbundance: 0, commonOre: null },
  { atomicNumber: 115, symbol: 'Mc', name: 'Moscovium', category: ElementCategory.Unknown, naturallyOccurring: false, synthetic: true, crustalAbundance: 0, commonOre: null },
  { atomicNumber: 116, symbol: 'Lv', name: 'Livermorium', category: ElementCategory.Unknown, naturallyOccurring: false, synthetic: true, crustalAbundance: 0, commonOre: null },
  { atomicNumber: 117, symbol: 'Ts', name: 'Tennessine', category: ElementCategory.Halogen, naturallyOccurring: false, synthetic: true, crustalAbundance: 0, commonOre: null },
  { atomicNumber: 118, symbol: 'Og', name: 'Oganesson', category: ElementCategory.NobleGas, naturallyOccurring: false, synthetic: true, crustalAbundance: 0, commonOre: null },
] as const;

export const NATURALLY_OCCURRING_ELEMENTS = ELEMENTS.filter(e => e.naturallyOccurring);
export const SYNTHETIC_ELEMENTS = ELEMENTS.filter(e => e.synthetic);
export const ELEMENT_BY_SYMBOL: ReadonlyMap<string, ElementData> = new Map(
  ELEMENTS.map(e => [e.symbol, e]),
);
export const ELEMENT_BY_ATOMIC_NUMBER: ReadonlyMap<number, ElementData> = new Map(
  ELEMENTS.map(e => [e.atomicNumber, e]),
);
